CREATE TABLE IF NOT EXISTS site_settings(id INTEGER PRIMARY KEY AUTOINCREMENT,site_name TEXT,tagline TEXT,purpose TEXT,about TEXT,hero_title TEXT,hero_subtitle TEXT,logo_url TEXT,hero_image_url TEXT,background_url TEXT,facebook_url TEXT);
CREATE TABLE IF NOT EXISTS classes(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,display_order INTEGER DEFAULT 0,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS subjects(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,icon TEXT DEFAULT '📘',display_order INTEGER DEFAULT 0,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS chapters(id INTEGER PRIMARY KEY AUTOINCREMENT,subject_id INTEGER NOT NULL,class_id INTEGER, title TEXT NOT NULL,description TEXT,display_order INTEGER DEFAULT 0,active INTEGER DEFAULT 1,FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE CASCADE,FOREIGN KEY(class_id) REFERENCES classes(id));
CREATE TABLE IF NOT EXISTS questions(id INTEGER PRIMARY KEY AUTOINCREMENT,subject_id INTEGER,chapter_id INTEGER,class_id INTEGER,question_text TEXT NOT NULL,question_type TEXT DEFAULT 'mcq',explanation TEXT,difficulty TEXT DEFAULT 'medium',marks INTEGER DEFAULT 1,active INTEGER DEFAULT 1,FOREIGN KEY(subject_id) REFERENCES subjects(id),FOREIGN KEY(chapter_id) REFERENCES chapters(id),FOREIGN KEY(class_id) REFERENCES classes(id));
CREATE TABLE IF NOT EXISTS question_options(id INTEGER PRIMARY KEY AUTOINCREMENT,question_id INTEGER NOT NULL,option_text TEXT NOT NULL,is_correct INTEGER DEFAULT 0,display_order INTEGER DEFAULT 0,FOREIGN KEY(question_id) REFERENCES questions(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS students(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,display_name TEXT,class_id INTEGER,practice_class_id INTEGER,email TEXT,phone TEXT,recovery_pin_hash TEXT,avatar_url TEXT,xp INTEGER DEFAULT 0,level INTEGER DEFAULT 1,streak INTEGER DEFAULT 0,last_active TEXT,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT,FOREIGN KEY(class_id) REFERENCES classes(id),FOREIGN KEY(practice_class_id) REFERENCES classes(id));
CREATE TABLE IF NOT EXISTS quizzes(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT,class_id INTEGER,subject_id INTEGER,chapter_id INTEGER,time_limit INTEGER DEFAULT 0,total_marks INTEGER DEFAULT 0,published INTEGER DEFAULT 0,question_count INTEGER DEFAULT 0,max_question_count INTEGER DEFAULT 50,student_can_choose_count INTEGER DEFAULT 0,randomize_questions INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(class_id) REFERENCES classes(id),FOREIGN KEY(subject_id) REFERENCES subjects(id),FOREIGN KEY(chapter_id) REFERENCES chapters(id));
CREATE TABLE IF NOT EXISTS quiz_questions(quiz_id INTEGER NOT NULL,question_id INTEGER NOT NULL,display_order INTEGER DEFAULT 0,PRIMARY KEY(quiz_id,question_id),FOREIGN KEY(quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,FOREIGN KEY(question_id) REFERENCES questions(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS quiz_attempts(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,quiz_id INTEGER NOT NULL,score INTEGER,total INTEGER,xp_earned INTEGER DEFAULT 0,started_at TEXT,completed_at TEXT,FOREIGN KEY(student_id) REFERENCES students(id),FOREIGN KEY(quiz_id) REFERENCES quizzes(id));
CREATE TABLE IF NOT EXISTS badges(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,icon TEXT,description TEXT,xp_threshold INTEGER DEFAULT 0,active INTEGER DEFAULT 1,display_order INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS student_badges(student_id INTEGER NOT NULL,badge_id INTEGER NOT NULL,earned_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(student_id,badge_id),FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE,FOREIGN KEY(badge_id) REFERENCES badges(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS notices(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,body TEXT NOT NULL,audience TEXT DEFAULT 'public',published INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS games(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,slug TEXT UNIQUE,description TEXT,type TEXT,launch_url TEXT,active INTEGER DEFAULT 1,display_order INTEGER DEFAULT 0,config TEXT);
CREATE TABLE IF NOT EXISTS admin_users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,active INTEGER DEFAULT 1);

CREATE INDEX IF NOT EXISTS idx_questions_class_subject ON questions(class_id,subject_id);
CREATE INDEX IF NOT EXISTS idx_chapters_class_subject ON chapters(class_id,subject_id);

CREATE TABLE IF NOT EXISTS media_assets(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,slot TEXT DEFAULT 'gallery',url TEXT NOT NULL,alt_text TEXT,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_media_assets_slot_active ON media_assets(slot,active);

CREATE TABLE IF NOT EXISTS quiz_attempt_questions(attempt_id INTEGER NOT NULL,question_id INTEGER NOT NULL,display_order INTEGER NOT NULL,PRIMARY KEY(attempt_id,display_order),FOREIGN KEY(attempt_id) REFERENCES quiz_attempts(id) ON DELETE CASCADE,FOREIGN KEY(question_id) REFERENCES questions(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_quiz_attempt_questions_attempt ON quiz_attempt_questions(attempt_id);
CREATE INDEX IF NOT EXISTS idx_quiz_attempt_questions_question ON quiz_attempt_questions(question_id);
